<a href="https://colab.research.google.com/github/Lukasz-Strzepek/data-science/blob/main/)1_wprowadzenie/01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Colab')

Hello Colab


In [ ]:
pip install numpy

In [2]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)


[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y = np.array([1.3, 2.3, 1.4])
print(y)

[1.3 2.3 1.4]


In [ ]:
y.dtype

dtype('float64')

2D Array


In [ ]:
x =np.array([[1, 2], [-3, 1]])


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.size

4

In [ ]:
x = np.array([[1,2,4], [4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

3D ARRAY


In [ ]:
x = np.array(
              [[[4,3,1],
                [3,1,2]],

              [[4,1,3],
               [4,2,1]],
               
               [[3,2,1],
                [4,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 3)

Typy danych

In [ ]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.2,2,3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
A

array([1., 2., 3.])

In [ ]:
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
A = np.array([1.2,2.8,3.4], dtype ='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24,120,230], dtype = np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24,120,230], dtype = np.uint8)
A.dtype

dtype('uint8')

Tworzenie tablic

In [ ]:
np.zeros(shape=(4,10), dtype = 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape =(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape =(5,5), dtype = 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [4]:
np.full(shape=(3,3), fill_value = 4, dtype = 'int')
np.full(shape=(4,4), fill_value = 5, dtype ='int')

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [5]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.arange(start = 1, stop = 15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(start=5, stop =100, step = 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [ ]:
np.arange(start=100, stop =50, step = -10) # nie włączy sie ostatni element

array([100,  90,  80,  70,  60])

In [ ]:
np.arange(start=0, stop=1, step=0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [ ]:
np.linspace(start=0, stop=1, num=10) # 10 równo rozlozonych elementow z tego przedziały

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
A.reshape((3,5)) # zmiana kształtu
A.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A.reshape((3,-1)) # -1 (3 wiersze i niech python dobierze liczbe kolumn = -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1,3)) # automatyczne dobieranie - -1, 3 kolumny wiec 5 wierszy

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A+B

array([6, 0, 7, 4])

In [ ]:
A - B

array([0, 2, 1, 0])

In [ ]:
A * B

array([ 9, -1, 12,  4])

In [11]:
A / B # tryb przy dzieleniu zawsze na float

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [12]:
np.add(A,B)

array([6, 0, 7, 4])

In [14]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [16]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [17]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
A * 3

array([ 9,  3, 12,  6])

In [ ]:
A + 3 *B

array([12, -2, 13,  8])

In [ ]:
X = np.array([[1, 3,], [-2,0]])
Y = np.array([[6,0,], [-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
X*Y

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X,Y) # mnożenie macierzowe

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y) #mnożenie macierzy nie jest przemienne

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)#mnożenie macieryz nie jest przemienne

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X @ Y # Mnożenie macierzowe, działanie nieprzemienne !

array([[  3,   6],
       [-12,   0]])

GENEROWANIE LICZB PSEUDOLOSOWYCH


In [19]:
np.random.seed(0)
np.random.seed(0)

In [20]:
np.random.randn() # losowa wartosc z rozkładu normalnego

1.764052345967664

In [ ]:
np.random.randn(10) # 10 wartosci z rozkladu normalnego

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4) # rozklad normalny

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [21]:
np.random.rand(10,3)# rozkład jednostajny

array([[0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504],
       [0.52889492, 0.56804456, 0.92559664],
       [0.07103606, 0.0871293 , 0.0202184 ],
       [0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 0.52184832],
       [0.41466194, 0.26455561, 0.77423369]])

In [22]:
np.random.rand() # rozklad jednostajny

0.45615033221654855

In [23]:
np.random.rand(10)

array([0.56843395, 0.0187898 , 0.6176355 , 0.61209572, 0.616934  ,
       0.94374808, 0.6818203 , 0.3595079 , 0.43703195, 0.6976312 ])

In [25]:
np.random.randint(10) # zwroci liczbe mniejsza niz 10 i calkowita losowo

9

In [26]:
np.random.randint(10)

9

In [28]:
np.random.randint(low=10, high = 101) # losowa liczba dwucyfrowa

45

In [29]:
np.random.randint(low=10, high = 101, size = 10) # size = 10

array([21, 56, 92, 10, 24, 63, 22, 52, 94, 85])

In [30]:
np.random.choice([3, 5, 4, 87]) # losowo, wybierze elemnt z iterowanego obiektu

3

In [32]:
np.random.choice(['sql', 'python', 'java'])


'java'

In [35]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.random.shuffle(data) # przetasowanie danych
data

array([4, 3, 9, 1, 7, 8, 6, 2, 0, 5])

PODSTAWOWE FUNKCJE NUMPY

In [38]:
np.exp(1)

2.718281828459045

In [39]:
np.sqrt(9)

3.0

In [40]:
np.all([2, 3, 1]) # bada kazdy element, czy true czy false

True

In [41]:
np.all([2, 0, 1])

False

In [42]:
np.any([4,0,0]) # sprawdza czy jakikolwiek obiekt jest prawda

True

In [43]:
np.any([0,0,0])

False

In [44]:
bool(0)

False

In [46]:
A = np.random.rand(5)
A

array([0.05571469, 0.45115921, 0.01998767, 0.44171092, 0.97958673])

In [48]:
np.argmax(A)#indeks gdzie tablica przyjmuje najwieksza wartosc 

4

In [49]:
A[np.argmax(A)] # wycinanie tego elemetu tablicy

0.9795867288127285

In [50]:
np.argmin(A) # najnizsza wartosc

2

In [51]:
np.argsort(A) # przydatne przy klasyfikacjiwieloklasowej, sortuje elemety podajac indeks np. jak chcemy zwrócic 3 najwieksze klasy

array([2, 0, 3, 1, 4])

In [52]:
np.max(A) # najwieksza

0.9795867288127285

In [53]:
np.min(A)

0.019987665408758737

In [54]:
np.mean(A) # srednia

0.3896318447385734

In [55]:
np.median(A) # mediana

0.44171092124884537

In [56]:
np.std(A) # odchylenie standardowe

0.3471835525351119

INDEKSOWANIE
WYCINANIE

```
# Sformatowano jako kod
```



In [59]:
A = np.arange(20)

In [ ]:
A#[idx], A[start:stop], A[:stop], A[start:]

In [60]:
A[2]

2

In [61]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [62]:
A[:2]

array([0, 1])

In [63]:
A[[0,2]] # indeks 0 i 2

array([0, 2])

In [64]:
A[-1] # indeksowanie od konca

19

In [67]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [68]:
A[0] # wytniemy wiersz

array([0, 1, 2, 3, 4])

In [69]:
A[1] # wiersz 2

array([5, 6, 7, 8, 9])

In [70]:
A[:, 0] # wycinanie kolumny

array([ 0,  5, 10, 15])

In [74]:
A[:, 4] # ostatania kolumna

array([ 4,  9, 14, 19])

In [73]:
A[:, -1] # rowniez ostatnia kolumna

array([ 4,  9, 14, 19])

In [75]:
A[1,1] #indeks dokladnie 1 wiwesz i 1 kolumna

6

In [76]:
A[1:2, 1:4] # fragemnty od do

array([[6, 7, 8]])

In [77]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [81]:
A[1,2] = 14 # zamiana po indeksach 7 na 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

ITERACJA PO TABLICACH

In [82]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [83]:
for row in A: # iterowanie po wierszach
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [84]:
for row in A: # iterowanie po 3 pierwszych wierszach
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [85]:
for item in A.flat: # iterowanie po kazdym elemencie tablicy nie tylko wierszach
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


ZMIANA ROZMAIRU RABLIC

In [90]:
A.shape


(4, 5)

In [91]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [87]:
A.reshape(5,4) # zmiana rozmiaru

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [88]:
A.ravel() # wypłaszczanie danych - do podstaci 1 wymiarowej

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [89]:
A.T # transponowanie macierzy kolumna na wiersz

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [93]:
A = np.arange(start=-10, stop =10, step = 0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [94]:
A.reshape(10,-1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [95]:
A > 0 # maska logiczna - zwróci prawde gdy wartosci wieksze od zera

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [96]:
A [A>0] # dzieki masce wycinamy tylko elementy wieksze od zera

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [98]:
np.bitwise_and(A>-5, A< 5) # end nie działa, maska gdzie oba waruki sa spelnione

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [99]:
A[np.bitwise_and(A>-5, A< 5)] # MASKA AND

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [100]:
A[np.bitwise_or(A<-5, A<5)] # maska OR albo mniejsze od -5 albo mniejsze od 5

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5])